version: "3"

services:
  api:
    #restart: always
    stdin_open: true
    tty: true
    build: ./Dockerfile
    image: docker-flask-test:latest
    volumes:
      - ./app:/deploy/app
      - ./flask.conf:/etc/nginx/sites-available/flask.conf
      - ./gunicorn.conf:/etc/supervisor/conf.d/gunicorn.conf
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "80:80"
    #command: '/bin/bash' 
    command: '/usr/bin/supervisord'
